### ISSUE TITLE
Setting Up Apache to host from Workspace

### ISSUE THREAD

**Issue by MrTidbury** [covcom/304CEM#5]
# Setting up Apache to view coverage Reports

### Installing Apache

Firstly need to check if Apache is installed to do this type

```sh
$ apache2
```
If it returns
```sh
$ -bash: apache2: command not found
```

Then apache2 still needs to be installed, this is done via the following commands;
```sh
$ sudo apt-get update
$ sudo apt install apache2
```
This should then install apache2 into your developement environment. However, by default apache2 only serves files located in /var/www and as a result will not be able to host the coverage reports generated by the test suite. This is achived by the following commands.

### Configuring Apache2
In all of the code below I make use of the editor Nano, however this can be switched out for vim or pico as required. Firsly run the following command.

```sh
$ sudo nano /etc/apache2/sites-available/000-default.conf 
```
Look for the following line:
```sh
 DocumentRoot /var/www/
```
And change it to the following
```sh
DocumentRoot ../../home/cabox/workspace/
```
Save and exit the file and then run,
```sh
$ sudo nano /etc/apache2/apache2.conf
```
Look for the documents parts of the file that look like the following and edit it to match mine below.
```sh
<Directory ../../home/cabox/workspace/ >
    Options FollowSymLinks
    AllowOverride None
    Require all granted
</Directory> 

<Directory /usr/share> 
    AllowOverride None
    Require all granted
</Directory>

<Directory />
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory> 
```
This has done two main things, firsly it has changed the directory that apache will serve files from to our main workspace folder. Secondly it allows requests from the root folder found at ```/``` to ```Require all granted``` allowing files to be served. Lastly the apache server needs to be restarted via the
```sh
sudo service apache2 restart
```
This should restart the server without any errors. All thats left is to right click and preview the file you want to view, and hopefully it should all work.

**Comment by marktyers** [comment]
Suggestions have been verified and added to worksheet 5, full credit given :)
